### ISSUE TITLE
Apartado salidas del proyecto.

### ISSUE THREAD

**Issue by jsm07** [damvelopers/cocinaeconomica#1]
En la ventana de salidas, tanto en el DataGridView y a la hora de crear una salida y modificar, debemos añadir un campo el cual indique donde ha salido, un ejemplo sería: Macarrones han salido a día 12/01/2017 en el comedor, o lo mismo pero en vez del comedor, ha salido a la guardería, o a otro de las entidades que pertenecen a la cocina económica.

**Comment by pablius93** [comment]
Sería una nueva tabla de 'clientes', que puedan incluir la info que necesiten (nombre, dirección, teléfono, ...) y que cuando vayan a añadir una salida indiquen a qué 'cliente' va

**Comment by pablo-moreno** [comment]
Sería una nueva tabla de 'clientes', que puedan incluir la info que necesiten (nombre, dirección, teléfono, ...) y que cuando vayan a añadir una producto a dónde ha salido
